##########
# Tribble with all files and meta-data corresponding to the method, panel and cancer type from it was obtained.
driver_result_files <- tribble(
  ~filename, ~method, ~panel, ~cancer_type,
  # MutsigCV
  "mutsig/WE_BRCA_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "BRCA",
  "mutsig/BCAST_BRCA_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "B-CAST", "BRCA",
  "mutsig/MSK_BRCA_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "BRCA",
  "mutsig/WE_LC_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "LC",
  "mutsig/MSK_LC_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "LC",
  "mutsig/WE_GBM_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "GBM",
  "mutsig/MSK_GBM_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "GBM",
  "mutsig/WE_OV_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "OV",
  "mutsig/MSK_OV_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "OV",
  "mutsig/WE_UCEC_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "UCEC",
  "mutsig/MSK_UCEC_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "UCEC",
  "mutsig/WE_KIRC_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "KIRC",
  "mutsig/MSK_KIRC_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "KIRC",
  "mutsig/WE_HNSC_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "HNSC",
  "mutsig/MSK_HNSC_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "HNSC",  
  "mutsig/WE_LGG_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "LGG",
  "mutsig/MSK_LGG_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "LGG",
  "mutsig/WE_THCA_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "THCA",
  "mutsig/MSK_THCA_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "THCA",
  "mutsig/WE_PRAD_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "PRAD",
  "mutsig/MSK_PRAD_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "PRAD",  
  "mutsig/WE_SKCM_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "SKCM",
  "mutsig/MSK_SKCM_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "SKCM",
  "mutsig/WE_COAD_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "COAD",
  "mutsig/MSK_COAD_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "COAD", 
  "mutsig/WE_STAD_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "STAD",
  "mutsig/MSK_STAD_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "STAD",
  "mutsig/WE_BLCA_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", NA, "BLCA",
  "mutsig/MSK_BLCA_TCGA_mutational.maf.sig_genes.txt", "MutSigCV", "MSK-IMPACT", "BLCA",
    

  # ActiveDriver
  "activedriver/WE_BRCA_output_activedriver", "ActiveDriver", NA, "BRCA",
  "activedriver/BCAST_BRCA_output_activedriver", "ActiveDriver", "B-CAST", "BRCA",
  "activedriver/MSK_BRCA_output_activedriver", "ActiveDriver", "MSK-IMPACT", "BRCA",
  "activedriver/WE_LC_output_activedriver", "ActiveDriver", NA, "LC",
  "activedriver/MSK_LC_output_activedriver", "ActiveDriver", "MSK-IMPACT", "LC",
  "activedriver/WE_GBM_output_activedriver", "ActiveDriver", NA, "GBM",
  "activedriver/MSK_GBM_output_activedriver", "ActiveDriver", "MSK-IMPACT", "GBM",
  "activedriver/WE_OV_output_activedriver", "ActiveDriver", NA, "OV",
  "activedriver/MSK_OV_output_activedriver", "ActiveDriver", "MSK-IMPACT", "OV",
  "activedriver/WE_UCEC_output_activedriver", "ActiveDriver", NA, "UCEC",
  "activedriver/MSK_UCEC_output_activedriver", "ActiveDriver", "MSK-IMPACT", "UCEC",
  "activedriver/WE_KIRC_output_activedriver", "ActiveDriver", NA, "KIRC",
  "activedriver/MSK_KIRC_output_activedriver", "ActiveDriver", "MSK-IMPACT", "KIRC",
  "activedriver/WE_HNSC_output_activedriver", "ActiveDriver", NA, "HNSC",
  "activedriver/MSK_HNSC_output_activedriver", "ActiveDriver", "MSK-IMPACT", "HNSC",
  "activedriver/WE_LGG_output_activedriver", "ActiveDriver", NA, "LGG",
  "activedriver/MSK_LGG_output_activedriver", "ActiveDriver", "MSK-IMPACT", "LGG",
  "activedriver/WE_THCA_output_activedriver", "ActiveDriver", NA, "THCA",
  "activedriver/MSK_THCA_output_activedriver", "ActiveDriver", "MSK-IMPACT", "THCA",
  "activedriver/WE_PRAD_output_activedriver", "ActiveDriver", NA, "PRAD",
  "activedriver/MSK_PRAD_output_activedriver", "ActiveDriver", "MSK-IMPACT", "PRAD",
  "activedriver/WE_SKCM_output_activedriver", "ActiveDriver", NA, "SKCM",
  "activedriver/MSK_SKCM_output_activedriver", "ActiveDriver", "MSK-IMPACT", "SKCM",
  "activedriver/WE_COAD_output_activedriver", "ActiveDriver", NA, "COAD",
  "activedriver/MSK_COAD_output_activedriver", "ActiveDriver", "MSK-IMPACT", "COAD",
  "activedriver/WE_STAD_output_activedriver", "ActiveDriver", NA, "STAD",
  "activedriver/MSK_STAD_output_activedriver", "ActiveDriver", "MSK-IMPACT", "STAD",
  "activedriver/WE_BLCA_output_activedriver", "ActiveDriver", NA, "BLCA",
  "activedriver/MSK_BLCA_output_activedriver", "ActiveDriver", "MSK-IMPACT", "BLCA",
  

  # OncodriveCLUSTL
  "oncodriveclustl/WE_BRCA_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "BRCA",
  "oncodriveclustl/BCAST_BRCA_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "B-CAST", "BRCA",
  "oncodriveclustl/MSK_BRCA_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "BRCA",
  "oncodriveclustl/WE_LC_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "LC",
  "oncodriveclustl/MSK_LC_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "LC",
  "oncodriveclustl/WE_GBM_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "GBM",
  "oncodriveclustl/MSK_GBM_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "GBM",
  "oncodriveclustl/WE_OV_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "OV",
  "oncodriveclustl/MSK_OV_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "OV",
  "oncodriveclustl/WE_UCEC_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "UCEC",
  "oncodriveclustl/MSK_UCEC_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "UCEC",
  "oncodriveclustl/WE_KIRC_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "KIRC",
  "oncodriveclustl/MSK_KIRC_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "KIRC",
  "oncodriveclustl/WE_HNSC_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "HNSC",
  "oncodriveclustl/MSK_HNSC_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "HNSC",  
  "oncodriveclustl/WE_LGG_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "LGG",
  "oncodriveclustl/MSK_LGG_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "LGG",
  "oncodriveclustl/WE_THCA_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "THCA",
  "oncodriveclustl/MSK_THCA_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "THCA",
  "oncodriveclustl/WE_PRAD_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "PRAD",
  "oncodriveclustl/MSK_PRAD_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "PRAD",  
  "oncodriveclustl/WE_SKCM_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "SKCM",
  "oncodriveclustl/MSK_SKCM_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "SKCM",
  "oncodriveclustl/WE_COAD_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "COAD",
  "oncodriveclustl/MSK_COAD_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "COAD", 
  "oncodriveclustl/WE_STAD_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "STAD",
  "oncodriveclustl/MSK_STAD_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "STAD",
  "oncodriveclustl/WE_BLCA_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", NA, "BLCA",
  "oncodriveclustl/MSK_BLCA_TCGA_mutational.tsv/elements_results.txt", "OncodriveCLUSTL", "MSK-IMPACT", "BLCA",

  
  # OncodriveFML
  "oncodrivefml/WE_BRCA_TCGA_mutational.tsv/WE_BRCA_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "BRCA",
  "oncodrivefml/BCAST_BRCA_TCGA_mutational.tsv/BCAST_BRCA_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "B-CAST", "BRCA",
  "oncodrivefml/MSK_BRCA_TCGA_mutational.tsv/MSK_BRCA_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "BRCA",
  "oncodrivefml/WE_LC_TCGA_mutational.tsv/WE_LC_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "LC",
  "oncodrivefml/MSK_LC_TCGA_mutational.tsv/MSK_LC_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "LC",
  "oncodrivefml/WE_GBM_TCGA_mutational.tsv/WE_GBM_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "GBM",
  "oncodrivefml/MSK_GBM_TCGA_mutational.tsv/MSK_GBM_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "GBM",
  "oncodrivefml/WE_OV_TCGA_mutational.tsv/WE_OV_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "OV",
  "oncodrivefml/MSK_OV_TCGA_mutational.tsv/MSK_OV_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "OV",
  "oncodrivefml/WE_UCEC_TCGA_mutational.tsv/WE_UCEC_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "UCEC",
  "oncodrivefml/MSK_UCEC_TCGA_mutational.tsv/MSK_UCEC_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "UCEC",
  "oncodrivefml/WE_KIRC_TCGA_mutational.tsv/WE_KIRC_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "KIRC",
  "oncodrivefml/MSK_KIRC_TCGA_mutational.tsv/MSK_KIRC_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "KIRC",
  "oncodrivefml/WE_HNSC_TCGA_mutational.tsv/WE_HNSC_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "HNSC",
  "oncodrivefml/MSK_HNSC_TCGA_mutational.tsv/MSK_HNSC_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "HNSC",  
  "oncodrivefml/WE_LGG_TCGA_mutational.tsv/WE_LGG_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "LGG",
  "oncodrivefml/MSK_LGG_TCGA_mutational.tsv/MSK_LGG_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "LGG",
  "oncodrivefml/WE_THCA_TCGA_mutational.tsv/WE_THCA_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "THCA",
  "oncodrivefml/MSK_THCA_TCGA_mutational.tsv/MSK_THCA_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "THCA",
  "oncodrivefml/WE_PRAD_TCGA_mutational.tsv/WE_PRAD_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "PRAD",
  "oncodrivefml/MSK_PRAD_TCGA_mutational.tsv/MSK_PRAD_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "PRAD",  
  "oncodrivefml/WE_SKCM_TCGA_mutational.tsv/WE_SKCM_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "SKCM",
  "oncodrivefml/MSK_SKCM_TCGA_mutational.tsv/MSK_SKCM_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "SKCM",
  "oncodrivefml/WE_COAD_TCGA_mutational.tsv/WE_COAD_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "COAD",
  "oncodrivefml/MSK_COAD_TCGA_mutational.tsv/MSK_COAD_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "COAD", 
  "oncodrivefml/WE_STAD_TCGA_mutational.tsv/WE_STAD_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "STAD",
  "oncodrivefml/MSK_STAD_TCGA_mutational.tsv/MSK_STAD_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "STAD",
  "oncodrivefml/WE_BLCA_TCGA_mutational.tsv/WE_BLCA_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", NA, "BLCA",
  "oncodrivefml/MSK_BLCA_TCGA_mutational.tsv/MSK_BLCA_TCGA_mutational-oncodrivefml.tsv.gz", "OncodriveFML", "MSK-IMPACT", "BLCA",
  
  
  #20/20+
  "plus2020/WE_BRCA_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "BRCA",
  "plus2020/BCAST_BRCA_TCGA_mutational.txt/oncogene.txt", "20/20+", "B-CAST", "BRCA",
  "plus2020/MSK_BRCA_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "BRCA",
  "plus2020/WE_LC_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "LC",
  "plus2020/MSK_LC_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "LC",
  "plus2020/WE_GBM_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "GBM",
  "plus2020/MSK_GBM_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "GBM",
  "plus2020/WE_OV_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "OV",
  "plus2020/MSK_OV_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "OV",
  "plus2020/WE_UCEC_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "UCEC",
  "plus2020/MSK_UCEC_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "UCEC",
  "plus2020/WE_KIRC_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "KIRC",
  "plus2020/MSK_KIRC_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "KIRC",
  "plus2020/WE_HNSC_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "HNSC",
  "plus2020/MSK_HNSC_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "HNSC",  
  "plus2020/WE_LGG_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "LGG",
  "plus2020/MSK_LGG_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "LGG",
  "plus2020/WE_THCA_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "THCA",
  "plus2020/MSK_THCA_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "THCA",
  "plus2020/WE_PRAD_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "PRAD",
  "plus2020/MSK_PRAD_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "PRAD",  
  "plus2020/WE_SKCM_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "SKCM",
  "plus2020/MSK_SKCM_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "SKCM",
  "plus2020/WE_COAD_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "COAD",
  "plus2020/MSK_COAD_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "COAD", 
  "plus2020/WE_STAD_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "STAD",
  "plus2020/MSK_STAD_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "STAD",
  "plus2020/WE_BLCA_TCGA_mutational.txt/oncogene.txt", "20/20+", NA, "BLCA",
  "plus2020/MSK_BLCA_TCGA_mutational.txt/oncogene.txt", "20/20+", "MSK-IMPACT", "BLCA",
  
  
  # dNdScv
  "dndscv/WE_BRCA_dndscv", "dNdScv", NA, "BRCA",
  "dndscv/BCAST_BRCA_TCGA_mutational", "dNdScv", "B-CAST", "BRCA",
  "dndscv/MSK_BRCA_dndscv", "dNdScv", "MSK-IMPACT", "BRCA",
  "dndscv/WE_LC_dndscv", "dNdScv", NA, "LC",
  "dndscv/MSK_LC_dndscv", "dNdScv", "MSK-IMPACT", "LC",
  "dndscv/WE_GBM_dndscv", "dNdScv", NA, "GBM",
  "dndscv/MSK_GBM_dndscv", "dNdScv", "MSK-IMPACT", "GBM",
  "dndscv/WE_OV_dndscv", "dNdScv", NA, "OV",
  "dndscv/MSK_OV_dndscv", "dNdScv", "MSK-IMPACT", "OV",
  "dndscv/WE_UCEC_dndscv", "dNdScv", NA, "UCEC",
  "dndscv/MSK_UCEC_dndscv", "dNdScv", "MSK-IMPACT", "UCEC",
  "dndscv/WE_KIRC_dndscv", "dNdScv", NA, "KIRC",
  "dndscv/MSK_KIRC_dndscv", "dNdScv", "MSK-IMPACT", "KIRC",
  "dndscv/WE_HNSC_dndscv", "dNdScv", NA, "HNSC",
  "dndscv/MSK_HNSC_dndscv", "dNdScv", "MSK-IMPACT", "HNSC",
  "dndscv/WE_LGG_dndscv", "dNdScv", NA, "LGG",
  "dndscv/MSK_LGG_dndscv", "dNdScv", "MSK-IMPACT", "LGG",
  "dndscv/WE_THCA_dndscv", "dNdScv", NA, "THCA",
  "dndscv/MSK_THCA_dndscv", "dNdScv", "MSK-IMPACT", "THCA",
  "dndscv/WE_PRAD_dndscv", "dNdScv", NA, "PRAD",
  "dndscv/MSK_PRAD_dndscv", "dNdScv", "MSK-IMPACT", "PRAD",
  "dndscv/WE_SKCM_dndscv", "dNdScv", NA, "SKCM",
  "dndscv/MSK_SKCM_dndscv", "dNdScv", "MSK-IMPACT", "SKCM",
  "dndscv/WE_COAD_dndscv", "dNdScv", NA, "COAD",
  "dndscv/MSK_COAD_dndscv", "dNdScv", "MSK-IMPACT", "COAD",
  "dndscv/WE_STAD_dndscv", "dNdScv", NA, "STAD",
  "dndscv/MSK_STAD_dndscv", "dNdScv", "MSK-IMPACT", "STAD",
  "dndscv/WE_BLCA_dndscv", "dNdScv", NA, "BLCA",
  "dndscv/MSK_BLCA_dndscv", "dNdScv", "MSK-IMPACT", "BLCA",
  
  
  # DriverML
  "driverml/WE_BRCA_TCGA_mutational_driverml", "DriverML", NA, "BRCA",
  "driverml/BCAST_BRCA_TCGA_mutational_driverml", "DriverML", "B-CAST", "BRCA",
  "driverml/MSK_BRCA_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "BRCA",
  "driverml/WE_LC_TCGA_mutational_driverml", "DriverML", NA, "LC",
  "driverml/MSK_LC_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "LC",
  "driverml/WE_GBM_TCGA_mutational_driverml", "DriverML", NA, "GBM",
  "driverml/MSK_GBM_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "GBM",
  "driverml/WE_OV_TCGA_mutational_driverml", "DriverML", NA, "OV",
  "driverml/MSK_OV_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "OV",
  "driverml/WE_UCEC_TCGA_mutational_driverml", "DriverML", NA, "UCEC",
  "driverml/MSK_UCEC_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "UCEC",
  "driverml/WE_KIRC_TCGA_mutational_driverml", "DriverML", NA, "KIRC",
  "driverml/MSK_KIRC_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "KIRC",
  "driverml/WE_HNSC_TCGA_mutational_driverml", "DriverML", NA, "HNSC",
  "driverml/MSK_HNSC_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "HNSC",
  "driverml/WE_LGG_TCGA_mutational_driverml", "DriverML", NA, "LGG",
  "driverml/MSK_LGG_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "LGG",
  "driverml/WE_THCA_TCGA_mutational_driverml", "DriverML", NA, "THCA",
  "driverml/MSK_THCA_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "THCA",
  "driverml/WE_PRAD_TCGA_mutational_driverml", "DriverML", NA, "PRAD",
  "driverml/MSK_PRAD_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "PRAD",
  "driverml/WE_SKCM_TCGA_mutational_driverml", "DriverML", NA, "SKCM",
  "driverml/MSK_SKCM_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "SKCM",
  "driverml/WE_COAD_TCGA_mutational_driverml", "DriverML", NA, "COAD",
  "driverml/MSK_COAD_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "COAD",
  "driverml/WE_STAD_TCGA_mutational_driverml", "DriverML", NA, "STAD",
  "driverml/MSK_STAD_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "STAD",
  "driverml/WE_BLCA_TCGA_mutational_driverml", "DriverML", NA, "BLCA",
  "driverml/MSK_BLCA_TCGA_mutational_driverml", "DriverML", "MSK-IMPACT", "BLCA"
  )
